spring.application.name=pilotoGW

spring.cloud.gateway.routes[0].id=planes-service
spring.cloud.gateway.routes[0].uri=https://planvuelo.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/planvuelo/**

spring.cloud.gateway.routes[1].id=registro-vuelo
spring.cloud.gateway.routes[1].uri=https://registrovuelo.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/registrovuelo/**
